version: "2"
services:
  master:
    image: vinniekaboom/jmeter_ubuntu:version-02
    tty: true
    ports:
      - "7000"
    networks:
      - jm-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
          constraints: [node.role == manager]
  slave:
    image: vinniekaboom/jmeter-server:version-01
    tty: true
    networks:
      - jm-network
    ports:
      - "7000"
      - "60000"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
networks:
  jm-network