version: "3.1"
services:
  master:
    image: vinsdocker/jmmaster
    tty: true
    ports:
      - "60000"
    networks:
      jm-network:
         ipv4_address: 10.5.0.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 120s
      placement:
          constraints: [node.role == manager]
  slave:
    image: vinsdocker/jmserver
    tty: true
    networks:
      jm-network:
         ipv4_address: 10.5.0.7
    ports:
      - "50000"
      - "1099"
    deploy:
      mode: global
      #replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 2
        window: 120s
      placement:
        constraints: [node.role == worker]
networks:
  jm-network:
     driver: overlay
     ipam:
       config:
         - subnet: 10.5.0.0/16
